### ISSUE TITLE
The plugin inserts multiple ^ characters in the airline

### ISSUE THREAD

**Issue by jclsn** [Roy-Orbison/airline-colour-splits#1]
It basically works, but messes up the airline for me

![grafik](https://user-images.githubusercontent.com/19779511/227947202-8cdad86b-9a47-4761-89f0-fc692bae8e1b.png)
![grafik](https://user-images.githubusercontent.com/19779511/227947284-0bb1098b-fb72-4316-8e75-2fad42cf17e8.png)

**Comment by Roy-Orbison** [comment]
From `:h hl-StatusLineNC` in Vim:

> ``` none
> StatusLineNC    status lines of not-current windows
>                 Note: If this is equal to "StatusLine", Vim will use "^^^" in
>                 the status line of the current window.
> ```

Basically your colour scheme ends up with the same values for both of those highlight groups, which is bad because then they're harder to differentiate. You can inspect them with `:hi StatusLine` and `:hi StatusLine`.

What scheme are you using? Have you tried any other schemes?
